### ISSUE TITLE
Python error running pkgcheck job

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1227]
The [job](https://github.com/gentoo-haskell/gentoo-haskell/runs/3976122423?check_suite_focus=true) fails due to a Python error:

```
2021-10-22T13:15:00.3601913Z [command]/opt/hostedtoolcache/Python/3.10.0/x64/bin/pmaint sync gentoo
2021-10-22T13:15:00.7318786Z *** syncing gentoo
2021-10-22T13:15:00.7453830Z Traceback (most recent call last):
2021-10-22T13:15:00.7454919Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 1348, in do_open
2021-10-22T13:15:00.7802785Z     h.request(req.get_method(), req.selector, req.data, headers,
2021-10-22T13:15:00.7804495Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1276, in request
2021-10-22T13:15:00.8113867Z     self._send_request(method, url, body, headers, encode_chunked)
2021-10-22T13:15:00.8115312Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1322, in _send_request
2021-10-22T13:15:00.8173214Z     self.endheaders(body, encode_chunked=encode_chunked)
2021-10-22T13:15:00.8174736Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1271, in endheaders
2021-10-22T13:15:00.8180345Z     self._send_output(message_body, encode_chunked=encode_chunked)
2021-10-22T13:15:00.8181772Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1031, in _send_output
2021-10-22T13:15:00.8186751Z     self.send(msg)
2021-10-22T13:15:00.8188171Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 969, in send
2021-10-22T13:15:00.8191845Z     self.connect()
2021-10-22T13:15:00.8192987Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1448, in connect
2021-10-22T13:15:00.8204849Z     self.sock = self._context.wrap_socket(self.sock,
2021-10-22T13:15:00.8205700Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ssl.py", line 512, in wrap_socket
2021-10-22T13:15:00.8568327Z     return self.sslsocket_class._create(
2021-10-22T13:15:00.8569368Z   File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ssl.py", line 1061, in _create
2021-10-22T13:15:00.8660056Z     self._sslobj = self._context._wrap_socket(
2021-10-22T13:15:00.8661047Z ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)
```

**Comment by hololeap** [comment]
Fixed upstream:

https://github.com/pkgcore/pkgcheck-action/issues/4#issuecomment-993316709
